"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 02:16:04.149133
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odds_event_id', sa.String(length=64), nullable=True),
    sa.Column('espn_event_id', sa.String(length=20), nullable=True),
    sa.Column('home_team', sa.String(length=60), nullable=False),
    sa.Column('away_team', sa.String(length=60), nullable=False),
    sa.Column('home_abbr', sa.String(length=6), nullable=True),
    sa.Column('away_abbr', sa.String(length=6), nullable=True),
    sa.Column('home_espn_id', sa.String(length=10), nullable=True),
    sa.Column('away_espn_id', sa.String(length=10), nullable=True),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'break', 'delayed', 'final', 'postponed', 'cancelled', name='event_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock_seconds', sa.Integer(), nullable=True),
    sa.Column('final_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_box_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_source', sa.Enum('espn_web', 'espn_site', 'espn_cdn', 'odds_api', 'nflverse', name='live_source', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('espn_event_id', name=op.f('uq_games_espn_event_id')),
    sa.UniqueConstraint('odds_event_id', name=op.f('uq_games_odds_event_id'))
    )
    op.create_index(op.f('ix_games_commence_time'), 'games', ['commence_time'], unique=False)
    op.create_table('lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('milliseconds', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookups'))
    )
    op.create_table('players',
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_espn_id', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('espn_athlete_id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_team_espn_id'), 'players', ['team_espn_id'], unique=False)
    op.create_table('source_health',
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('state', sa.Enum('ok', 'degraded', 'open', name='health_state', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('failure_kind', sa.Enum('transient', 'blocked', 'throttled', 'schema', 'implausible', 'frozen', name='failure_kind', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('requests_last_hour', sa.Integer(), nullable=False),
    sa.Column('errors_last_hour', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_source_health'))
    )
    op.create_table('hot_games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('last_lookup_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_hot_games_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_hot_games'))
    )
    op.create_table('live_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=False),
    sa.Column('stat', sa.Enum('receptions', 'receiving_yards', 'receiving_tds', 'longest_reception', 'rushing_yards', 'rush_attempts', 'rush_tds', 'longest_rush', 'passing_yards', 'pass_completions', 'pass_attempts', 'pass_tds', 'interceptions_thrown', 'touchdowns', 'field_goals', 'kicking_points', 'sacks', 'tackles_assists', 'solo_tackles', 'def_interceptions', name='stat', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('source', sa.Enum('espn_web', 'espn_site', 'espn_cdn', 'odds_api', 'nflverse', name='stat_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_live_stats_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'espn_athlete_id', 'stat', name=op.f('pk_live_stats'))
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('live', 'historical', name='snapshot_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('slot', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendor_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('markets', sa.Text(), nullable=False),
    sa.Column('books', sa.Text(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload_gzip', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_odds_snapshots_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    op.create_index(op.f('ix_odds_snapshots_game_id'), 'odds_snapshots', ['game_id'], unique=False)
    op.create_index('ix_odds_snapshots_game_observed', 'odds_snapshots', ['game_id', 'observed_at'], unique=False)
    op.create_table('player_name_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('auto', 'doubtful', 'unmapped')", name=op.f('ck_player_name_map_status_valid')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_player_name_map_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_name_map')),
    sa.UniqueConstraint('game_id', 'raw_name', name='uq_player_name_map_game_raw')
    )
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('espn_play_id', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock', sa.String(length=8), nullable=True),
    sa.Column('wallclock', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('yards', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=True),
    sa.Column('team_espn_id', sa.String(length=10), nullable=True),
    sa.Column('scoring', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_plays_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plays')),
    sa.UniqueConstraint('espn_play_id', name=op.f('uq_plays_espn_play_id'))
    )
    op.create_index(op.f('ix_plays_game_id'), 'plays', ['game_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=40), nullable=False),
    sa.Column('market_key', sa.String(length=60), nullable=False),
    sa.Column('market_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=True),
    sa.Column('point', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('american', sa.Integer(), nullable=False),
    sa.CheckConstraint('american >= 100 OR american <= -100', name=op.f('ck_prices_odds_valid')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_prices_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['odds_snapshots.id'], name=op.f('fk_prices_snapshot_id_odds_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    op.create_index('ix_prices_lookup', 'prices', ['game_id', 'market_key', 'espn_athlete_id'], unique=False)
    op.create_index('ix_prices_snapshot', 'prices', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_snapshot', table_name='prices')
    op.drop_index('ix_prices_lookup', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_plays_game_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_table('player_name_map')
    op.drop_index('ix_odds_snapshots_game_observed', table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_game_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_table('live_stats')
    op.drop_table('hot_games')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_players_team_espn_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('lookups')
    op.drop_index(op.f('ix_games_commence_time'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
