"""nflverse verification

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 03:39:07.488876
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=False),
    sa.Column('stat', sa.Enum('receptions', 'receiving_yards', 'receiving_tds', 'longest_reception', 'rushing_yards', 'rush_attempts', 'rush_tds', 'longest_rush', 'passing_yards', 'pass_completions', 'pass_attempts', 'pass_tds', 'interceptions_thrown', 'touchdowns', 'field_goals', 'kicking_points', 'sacks', 'tackles_assists', 'solo_tackles', 'def_interceptions', name='correction_stat', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('source', sa.Enum('espn_web', 'espn_site', 'espn_cdn', 'odds_api', 'nflverse', name='correction_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_stat_corrections_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stat_corrections'))
    )
    op.create_index(op.f('ix_stat_corrections_game_id'), 'stat_corrections', ['game_id'], unique=False)
    op.add_column('games', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('live_stats', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_stats', 'verified_at')
    op.drop_column('games', 'verified_at')
    op.drop_index(op.f('ix_stat_corrections_game_id'), table_name='stat_corrections')
    op.drop_table('stat_corrections')
    # ### end Alembic commands ###
