"""deciding plays

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 03:51:37.562177
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deciding_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('espn_athlete_id', sa.String(length=20), nullable=False),
    sa.Column('stat', sa.Enum('receptions', 'receiving_yards', 'receiving_tds', 'longest_reception', 'rushing_yards', 'rush_attempts', 'rush_tds', 'longest_rush', 'passing_yards', 'pass_completions', 'pass_attempts', 'pass_tds', 'interceptions_thrown', 'touchdowns', 'field_goals', 'kicking_points', 'sacks', 'tackles_assists', 'solo_tackles', 'def_interceptions', name='deciding_stat', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('exact', sa.Boolean(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock', sa.String(length=8), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.Column('play_id', sa.Integer(), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_deciding_plays_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['play_id'], ['plays.id'], name=op.f('fk_deciding_plays_play_id_plays'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deciding_plays'))
    )
    op.create_index('ix_deciding_plays_lookup', 'deciding_plays', ['game_id', 'espn_athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deciding_plays_lookup', table_name='deciding_plays')
    op.drop_table('deciding_plays')
    # ### end Alembic commands ###
