"""first td check

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 13:38:49.556402
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_td_official', sa.String(length=20), nullable=True))
    op.add_column('games', sa.Column('first_td_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'first_td_checked_at')
    op.drop_column('games', 'first_td_official')
    # ### end Alembic commands ###
